[pytest]
minversion = 7.0
testpaths =
    "arccnet"
    "docs"
norecursedirs =
    ".tox"
    "build"
    "docs/_build"
    "docs/generated"
    "*.egg-info"
    "examples"
    ".jupyter"
    ".history"
    "tools"
    "notebooks"
doctest_plus = disabled
text_file_format = rst
addopts = --doctest-rst --import-mode=importlib --ignore-glob=*/arccnet/models/fulldisk/utils.py --ignore-glob=*/arccnet/models/fulldisk/yolo/yolo_labels_visualization.py
remote_data_strict = True
filterwarnings =
