"""Configuration for binary flare classification."""

import os

MODEL_NAME = "vit_base_patch8_224"

BATCH_SIZE = 64
NUM_WORKERS = 16
MAX_EPOCHS = 500
RANDOM_SEED = 42
PATIENCE = 15
CHECKPOINT_METRIC = "val_f1"

ACCELERATOR = "auto"
DEVICES = [2]
PRECISION = "16-mixed"

LOSS_FUNCTION = "weighted_bce"  # Options: "bce", "weighted_bce", "focal"
FOCAL_ALPHA = 0.9
FOCAL_GAMMA = 2.0

USE_LR_FINDER = True
LEARNING_RATE = 1e-4

DATA_FOLDER = os.getenv("ARCAFF_DATA_FOLDER", "/ARCAFF/data")
FLARES_PARQ = "mag-pit-flare-dataset_1996-01-01_2023-01-01_dev.parq"
CUTOUT_DATASET_FOLDER = "arcnet-v20251017/04_final"

THRESHOLD_CLASS = "M"
TARGET_COLUMN = f"flares_above_{THRESHOLD_CLASS}"
IMAGE_TYPE = "magnetograms"

TEST_SIZE = 0.1
VAL_SIZE = 0.2

DEFAULT_DECISION_THRESHOLD = 0.5
ENABLE_THRESHOLD_TUNING = True
THRESHOLD_TUNING_OBJECTIVE = "f1"
THRESHOLD_TUNING_SPLIT = "val"
THRESHOLD_SEARCH_METHOD = "unique_probs_exact"

IMG_TARGET_HEIGHT = 224
IMG_TARGET_WIDTH = 224
IMG_DIVISOR = 800.0
IMG_MIN_VAL = -1.0
IMG_MAX_VAL = 1.0

PIN_MEMORY = True
PERSISTENT_WORKERS = False
PREFETCH_FACTOR = 1
DATALOADER_MULTIPROCESSING_CONTEXT = None

ENABLE_COMET_LOGGING = True
COMET_PROJECT_NAME = "ars-flare-classification"
COMET_WORKSPACE = "arcaff"

APPLY_QUALITY_FILTER = True
APPLY_PATH_FILTER = True
APPLY_LONGITUDE_FILTER = True
MAX_LONGITUDE = 65.0
APPLY_NAN_FILTER = True
NAN_THRESHOLD = 0.05
