"""Configuration for multiclass flare classification."""

import os

MODEL_NAME = "vit_base_patch32_224"
PRETRAINED = False
USE_WEIGHTED_LOSS = True
LOSS_TYPE = "focal"
FOCAL_ALPHA = 1.0
FOCAL_GAMMA = 2.0
ACCELERATOR = "auto"
DEVICES = "auto"
PRECISION = "16-mixed"

BATCH_SIZE = 64
NUM_WORKERS = os.cpu_count() // 2 if os.cpu_count() else 1
LEARNING_RATE = 1e-4
MAX_EPOCHS = 500
RANDOM_SEED = 42
PATIENCE = 10
CHECKPOINT_METRIC = "val_f1"

DATA_FOLDER = os.getenv("ARCAFF_DATA_FOLDER", "/ARCAFF/data")
FLARES_PARQ = "mag-pit-flare-dataset_1996-01-01_2023-01-01_dev.parq"
CUTOUT_DATASET_FOLDER = "arcnet-v20251017/04_final"

CLASSES = ["Quiet", "C", "M_X"]
TARGET_COLUMN = "flare_class"

TEST_SIZE = 0.1
VAL_SIZE = 0.2
N_FOLDS = 5
SPLIT_CACHE_DIR = None

FILTER_SOLAR_LIMB = True
MAX_LONGITUDE = 65.0
MAX_LATITUDE = None
LIMB_DISTANCE_THRESHOLD = None

IMG_TARGET_HEIGHT = 224
IMG_TARGET_WIDTH = 224
IMG_DIVISOR = 800.0
IMG_MIN_VAL = -1.0
IMG_MAX_VAL = 1.0

PIN_MEMORY = True
PERSISTENT_WORKERS = False
PREFETCH_FACTOR = 1
DATALOADER_MULTIPROCESSING_CONTEXT = None

USE_AUGMENTATION = True
HORIZONTAL_FLIP_PROB = 0.5
VERTICAL_FLIP_PROB = 0.5
ROTATION_DEGREES = 10

ENABLE_COMET_LOGGING = True
COMET_PROJECT_NAME = "flares-multiclass"
COMET_WORKSPACE = "arcaff"

LOG_CONFUSION_MATRIX = True
LOG_MISCLASSIFIED_EXAMPLES = True
MAX_MISCLASSIFIED_EXAMPLES = 20
LOG_CLASSIFICATION_REPORT = True

APPLY_QUALITY_FILTER = True
APPLY_PATH_FILTER = True
APPLY_LONGITUDE_FILTER = False
APPLY_NAN_FILTER = False
NAN_THRESHOLD = 0.05
